# Generated by Django 4.1.6 on 2023-03-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id_candidat', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('nationalite', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('permis_conduire', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_c', models.URLField(blank=True, null=True)),
                ('competences_techniques', models.TextField(blank=True, null=True)),
                ('competences_linguistiques', models.TextField(blank=True, null=True)),
                ('competences_sociales', models.TextField(blank=True, null=True)),
                ('niveau_etudes', models.CharField(max_length=50)),
                ('domaine_expertise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('siege_social', models.CharField(max_length=100)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('type_offre', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('competences', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('diplomes', models.TextField(blank=True, null=True)),
                ('lieu_travail', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(max_length=50)),
                ('duree_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('salaire', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('avantages', models.TextField(blank=True, null=True)),
                ('nombre_postes', models.IntegerField(blank=True, null=True)),
                ('langues', models.CharField(blank=True, max_length=100, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.candidat')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.entreprise')),
                ('offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.offre')),
            ],
            options={
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
