# Generated by Django 4.1.6 on 2023-03-13 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id_candidate', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('driving_license', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('language_skills', models.TextField(blank=True, null=True)),
                ('social_skills', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=50)),
                ('expertise_field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('business_sector', models.CharField(max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('degrees', models.TextField(blank=True, null=True)),
                ('workplace', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=50)),
                ('contract_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('number_of_positions', models.IntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='offre',
            name='entreprise',
        ),
        migrations.RenameField(
            model_name='postulation',
            old_name='date_postulation',
            new_name='application_date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='log',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='log',
            name='offre',
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='log',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.candidate'),
        ),
        migrations.AddField(
            model_name='log',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.company'),
        ),
        migrations.AddField(
            model_name='log',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.offer'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='candidate',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Agence.candidate'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='offer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Agence.offer'),
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together={('candidate', 'offer')},
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='offre',
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
