# Generated by Django 4.1.6 on 2023-03-14 14:03

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0002_candidate_company_offer_remove_offre_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='company',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
