# Generated by Django 4.1.6 on 2023-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0004_historicalcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
    ]
