# Generated by Django 4.1.6 on 2023-03-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0005_delete_historicalcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='modified',
        ),
    ]
