# Generated by Django 4.1.6 on 2023-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0006_remove_company_created_remove_company_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='company',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
