# Generated by Django 4.1.6 on 2023-03-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0008_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='offer',
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='postulation',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Postulation',
        ),
    ]
