# Generated by Django 4.1.6 on 2023-03-15 10:24

import django.contrib.auth.password_validation
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0009_remove_log_candidate_remove_log_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id_candidate', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('driving_license', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('language_skills', models.TextField(blank=True, null=True)),
                ('social_skills', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=50)),
                ('expertise_field', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password])),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('degrees', models.TextField(blank=True, null=True)),
                ('workplace', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=50)),
                ('contract_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('number_of_positions', models.IntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.company')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.candidate')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('candidate', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Agence.candidate')),
                ('offer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Agence.offer')),
            ],
            options={
                'unique_together': {('candidate', 'offer')},
            },
        ),
    ]
