# Generated by Django 4.1.6 on 2023-03-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0010_candidate_offer_log_postulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agence.company'),
        ),
    ]
