# Generated by Django 4.1.7 on 2023-03-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0017_remove_log_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='candidate',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Agence.candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together={('candidate', 'offer')},
        ),
    ]
