# Generated by Django 4.1.7 on 2023-03-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0019_log_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.candidate'),
        ),
    ]
