# Generated by Django 4.1.7 on 2023-03-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0020_alter_log_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agence.candidate'),
        ),
    ]
