# Generated by Django 4.1.6 on 2023-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0021_alter_log_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='candidate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
