# Generated by Django 4.1.6 on 2023-03-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0024_alter_log_candidate_alter_log_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='degrees',
            new_name='education_level',
        ),
    ]
