# Generated by Django 4.1.6 on 2023-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0025_rename_degrees_offer_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
