# Generated by Django 4.1.6 on 2023-04-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0027_postulation_acceptation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postulation',
            unique_together=set(),
        ),
    ]
