# Generated by Django 4.1.6 on 2023-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0028_alter_postulation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
