# Generated by Django 4.1.6 on 2023-04-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0029_offer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='city',
        ),
    ]
